---
notifications:
  email:
  - team@appwrite.io

dist: xenial

language: shell

arch:
  - amd64
  # - arm64

os: linux

before_install:
  - curl -fsSL https://get.docker.com | sh
  - echo '{"experimental":"enabled"}' | sudo tee /etc/docker/daemon.json
  - mkdir -p $HOME/.docker
  - echo '{"experimental":"enabled"}' | sudo tee $HOME/.docker/config.json
  - sudo service docker start
  - >
    if [ ! -z "${DOCKERHUB_PULL_USERNAME:-}" ]; then
      echo "${DOCKERHUB_PULL_PASSWORD}" | docker login --username "${DOCKERHUB_PULL_USERNAME}" --password-stdin
    fi
  - docker --version
  - docker run --rm --privileged linuxkit/binfmt:v0.8
  - docker buildx create --use

install:
  - docker-compose up -d

script:
  - docker ps -a
  - docker-compose logs maildev
  - >
    if : >/dev/tcp/localhost/1080; then
      echo 'HTTP connection available.'
      travis_terminate 0
    else
      echo 'HTTP connection unavailable.'
      travis_terminate 1
    fi
  - >
    if : >/dev/tcp/localhost/1025; then
      echo 'SMTP connection available.'
      travis_terminate 0
    else
      echo 'SMTP connection unavailable.'
      travis_terminate 1
    fi

deploy:
  - provider: script
    edge: true
    script: docker buildx build --platform linux/amd64,linux/arm64,linux/arm/v7,linux/arm/v6,linux/ppc64le,linux/s390x -t appwrite/mailcatcher:$TRAVIS_TAG ./ --push
    on:
      tags: true